# Generated by Django 5.1.3 on 2025-03-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencompass', '0002_ce_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ce_type',
            name='type',
            field=models.CharField(default=0, help_text='数据类型', max_length=42),
            preserve_default=False,
        ),
    ]
