# Generated by Django 5.1.3 on 2025-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencompass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ce_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=200, unique=True)),
                ('address', models.CharField(help_text='类型地址', max_length=42)),
            ],
            options={
                'verbose_name': 'CE类型',
                'verbose_name_plural': 'CE类型',
                'ordering': ['-id'],
            },
        ),
    ]
